// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: proto/protos/winner.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WinnerService_GetWinnersByGameId_FullMethodName = "/game.WinnerService/GetWinnersByGameId"
)

// WinnerServiceClient is the client API for WinnerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WinnerServiceClient interface {
	GetWinnersByGameId(ctx context.Context, in *GameId, opts ...grpc.CallOption) (*DivisionResults, error)
}

type winnerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWinnerServiceClient(cc grpc.ClientConnInterface) WinnerServiceClient {
	return &winnerServiceClient{cc}
}

func (c *winnerServiceClient) GetWinnersByGameId(ctx context.Context, in *GameId, opts ...grpc.CallOption) (*DivisionResults, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DivisionResults)
	err := c.cc.Invoke(ctx, WinnerService_GetWinnersByGameId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WinnerServiceServer is the server API for WinnerService service.
// All implementations must embed UnimplementedWinnerServiceServer
// for forward compatibility.
type WinnerServiceServer interface {
	GetWinnersByGameId(context.Context, *GameId) (*DivisionResults, error)
	mustEmbedUnimplementedWinnerServiceServer()
}

// UnimplementedWinnerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWinnerServiceServer struct{}

func (UnimplementedWinnerServiceServer) GetWinnersByGameId(context.Context, *GameId) (*DivisionResults, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWinnersByGameId not implemented")
}
func (UnimplementedWinnerServiceServer) mustEmbedUnimplementedWinnerServiceServer() {}
func (UnimplementedWinnerServiceServer) testEmbeddedByValue()                       {}

// UnsafeWinnerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WinnerServiceServer will
// result in compilation errors.
type UnsafeWinnerServiceServer interface {
	mustEmbedUnimplementedWinnerServiceServer()
}

func RegisterWinnerServiceServer(s grpc.ServiceRegistrar, srv WinnerServiceServer) {
	// If the following call pancis, it indicates UnimplementedWinnerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WinnerService_ServiceDesc, srv)
}

func _WinnerService_GetWinnersByGameId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GameId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WinnerServiceServer).GetWinnersByGameId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WinnerService_GetWinnersByGameId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WinnerServiceServer).GetWinnersByGameId(ctx, req.(*GameId))
	}
	return interceptor(ctx, in, info, handler)
}

// WinnerService_ServiceDesc is the grpc.ServiceDesc for WinnerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WinnerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "game.WinnerService",
	HandlerType: (*WinnerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWinnersByGameId",
			Handler:    _WinnerService_GetWinnersByGameId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/protos/winner.proto",
}
